version: '3'
services:
  frontend:
    build: frontend/  #Especificamos o contexto, ou seja, a pasta onde est치 o Dockerfile <- Ser치 executado o build - RUN
    restart: on-failure # O container ser치 reiniciado caso ocorra alguma falha apontaada pelo exit code (!= 0)
    ports:
      - 3000:3000 # PortaHost:PortaContainer
    depends_on:
      - backend
    volumes:
      - ./logs:/var/log/frontend
    networks:
      - rede-virtual-1
  backend:
    build: backend/ # <- Ser치 executado o build - RUN
    restart: on-failure
    ports:
      - 3001:3001
    environment:
      - DB_HOST=database 
    depends_on:
      - database
    networks:
      - rede-virtual-1
      - rede-virtual-2
  database:
    image: betrybe/docker-compose-example-database:v1 # Especificamos a Imagem Docker diretamente - RUN
    restart: on-failure
    volumes:
      - dados-do-banco:/data/db # nome-do-volume : caminho-no-container-para-montar
    networks:
      - rede-virtual-2

volumes: # Especificamos que deve ser criado um volume virtual
  dados-do-banco: # nome do volume virtual criado

networks:
  rede-virtual-1:
  rede-virtual-2: